name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag felsc/fft.gateway:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secret.username}}
        password: ${{secret.password}}
    - name: Push the Docker image
      run: docker push felsc/fft.gateway
